apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  labels:
    app: postgres
    {{- include "examkube_chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.db.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.password | quote }}
  POSTGRES_DB: {{ .Values.db.name | quote }}

