apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  labels:
    app: fastapi
    {{- include "examkube_chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.db.user | quote }}
  DB_PASSWORD: {{ .Values.db.password | quote }}

