apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.host }}
  labels:
    app: postgres
    {{- include "examkube_chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: pg
      port: {{ default 5432 .Values.db.port | int }}
      targetPort: {{ default 5432 .Values.db.port | int }}

